# Generated by Django 5.0.2 on 2024-02-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('Community_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.location')),
            ],
        ),
        migrations.CreateModel(
            name='Camera_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn_time', models.DateTimeField()),
                ('checkOut_time', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.camera')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.person')),
            ],
        ),
        migrations.CreateModel(
            name='Person_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn_time', models.DateTimeField()),
                ('checkOut_time', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.camera')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.location')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.person')),
            ],
        ),
        migrations.CreateModel(
            name='UsersInCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('Community_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.community')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.person')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(through='eagle.UsersInCommunity', to='eagle.person'),
        ),
    ]
