# Generated by Django 5.0.3 on 2024-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
