# Generated by Django 5.0.3 on 2024-03-06 17:36

import eagle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0003_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to=eagle.models.get_photo_path),
        ),
    ]
