# Generated by Django 5.0.3 on 2024-03-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person_History',
        ),
    ]
