# Generated by Django 4.2.3 on 2024-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0005_delete_person_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True),
        ),
    ]
