# Generated by Django 4.2.3 on 2024-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0006_person_password_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
