# Generated by Django 5.0.3 on 2024-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0008_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='username', max_length=150),
        ),
    ]
