# Generated by Django 5.0.3 on 2024-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0010_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Community_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
