# Generated by Django 5.0.3 on 2024-05-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0011_alter_community_community_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
    ]
