# Generated by Django 5.0.4 on 2024-05-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0011_adminloginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloginhistory',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagle.admin'),
        ),
    ]
