# Generated by Django 5.0.4 on 2024-05-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0012_alter_adminloginhistory_admin'),
        ('eagle', '0012_remove_community_name'),
    ]

    operations = [
    ]
