# Generated by Django 5.0.4 on 2024-05-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0015_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='phone_number',
            new_name='phoneno',
        ),
    ]
